apiVersion: v1
kind: Service
metadata:
  name: jx-payments
spec:
  selector:
    app: jx-payments
  ports:
  - protocole: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jx-payments
spec:
  selector:
    matchLabels:
      app: jx-payments
  replicas: 1
  template:
    metadata:
      labels:
      app: jx-payments
    spec:
      containers:
      - name: jx-payments
      image: mmontalvogaete/jx_payments:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8000

