apiVersion: v1
kind: Service
metadata:
  labels:
    app: jx-payments
  name: jx-payments
spec:
  ports:
  - name: 80-80
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jx-payments
  type: NodePort